### ISSUE TITLE
Update DB Login in Vagrant File

### ISSUE THREAD

**Issue by TravisSperry** [paircolumbus/pairs2#16]
DB username and password need to be updated in vagrant file.

**Comment by TravisSperry** [comment]
`FATAL: password authentication failed for user "postgres" FATAL: password authentication failed for user "postgres"`

**Comment by davidmyersdev** [comment]
This is happening because the default configuration is set to use the default user with a non-default password. I could definitely fix this in the provisioning script, but the better solution would be to use a non-default user or use the default password for the default user.

**Comment by davidmyersdev** [comment]
For now, I think I'm going to go with the provisioning script route just to ensure this doesn't happen in the future.

**Comment by davidmyersdev** [comment]
After more thought, this should be a feature of the script anyway so I have updated it. Testing now and will close the issue if it works.

**Comment by davidmyersdev** [comment]
Fixed in the last commit.
