### ISSUE TITLE
Which style framework should we use?

### ISSUE THREAD

**Issue by TravisSperry** [paircolumbus/pairs2#21]
Bootstrap? Seems like a reasonable choice.

**Comment by TravisSperry** [comment]
I added bootstrap in #27

**Comment by degoeym** [comment]
Bootstrap is sufficient unless anyone is good at site design. I know some of the Columbus Web Group people will make fun of us, though. 😝

**Comment by TravisSperry** [comment]
We can use it as the base framework and then make modifications such that it's not super bootstrappy.
