### ISSUE TITLE
Center sign up page content.

### ISSUE THREAD

**Issue by degoeym** [paircolumbus/pairs2#32]
Looks weird to go from a page where content is centered to one where it's not, so I'mma fix it.

**Comment by erinmadisonanthony** [comment]
Hey @degoeym - make sure you pull down the code we just merged in for the new sign up page. I just created a new one with the Devise gem.

**Comment by erinmadisonanthony** [comment]
I didn't bother styling it though, so it does still need to be centered.

**Comment by degoeym** [comment]
Yeah, went to push and it told me I had to get latest, which I did. Fix is in.

**Comment by erinmadisonanthony** [comment]
Great, thanks!

**Comment by erinmadisonanthony** [comment]
Hey, so... Travis and I just deleted that sign up page since we had a duplicate and most of the functionality we needed was on the other one. If you feel like styling the Devise sign up page, please feel free!

**Comment by degoeym** [comment]
This involves changes to both the sign up and sign in pages, not just the sign up page as the issue title indicates. The content on each page is centered now so it's not all crammed to the left side.
